apiVersion: skaffold/v2beta18
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: react-reload
    context: app
    sync:
      manual:
      - src: 'src/components/*'
        dest: .
      - src: 'src/styles/*'
        dest: .
deploy:
  docker:
    images: [react-reload]
    useCompose: false
portForward:
- resourceType: Container
  resourceName: react-reload
  port: 8080
  localPort: 9000
