apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      values:
        image: skaffold-helm
